# Binary Sensors Configuration
# Includes trend sensors for G2 valve detection

# ============================================================================
# TREND SENSORS - Detect Temperature Rise for G2 Valve Detection
# ============================================================================
# These detect when a tank temperature is actively RISING (being heated)
# More reliable than static delta-T measurements

# DHW Tank Heating Trend
# Detects when DHW tank temperature is rising
- platform: trend
  sensors:
    dhw_tank_heating_trend:
      friendly_name: "DHW Tank Heating Trend"
      entity_id: sensor.dhw_tank_temperature
      device_class: heat
      sample_duration: 300  # Look at last 5 minutes of data
      min_gradient: 0.0017  # Minimum rise rate: 0.1°F/min (0.1/60 seconds)
      max_samples: 10  # Use 10 samples over the 5-minute window

# Buffer Tank Heating Trend
# Detects when buffer tank temperature is rising
- platform: trend
  sensors:
    buffer_tank_heating_trend:
      friendly_name: "Buffer Tank Heating Trend"
      entity_id: sensor.shelly_plus_buffer_tank_temperature
      device_class: heat
      sample_duration: 300  # Look at last 5 minutes of data
      min_gradient: 0.0017  # Minimum rise rate: 0.1°F/min (0.1/60 seconds)
      max_samples: 10  # Use 10 samples over the 5-minute window
