# Use the STATISTICS platform instead of FILTER
- platform: statistics
  name: "House Heat Loss Coefficient (kW/C) - Time Mean"
  unique_id: "house_heat_loss_coefficient_kw_c_time_mean"
  entity_id: sensor.house_heat_loss_coefficient_kw_c
  state_characteristic: mean
  # This calculates the mean of all data points over the last 60 minutes
  max_age:
    hours: 1
  sampling_size: 1000  # Set a high sampling size for accuracy
  precision: 2

- platform: statistics
  name: "HVAC Flow Rate Average"
  entity_id: sensor.hvac_buffer_tank_flow_rate
  unique_id: hvac_flow_rate_average
  state_characteristic: average_linear
  max_age:
    minutes: 1
  precision: 1  


# ------------------------------------------------------------------------
# NOTE: Power/Grid sensors have been migrated to sensors/template/grid_power_sensors.yaml
# ------------------------------------------------------------------------
# COMMENTED OUT FOR RESET - Uncomment after restart to recreate with 0 values
# ------------------------------------------------------------------------
- platform: integration
  source: sensor.heat_pump_electrical_power_input
  name: "Heat_pump Input Power Interval"
  unique_id: heat_pump_input_power_interval_kwh
  unit_prefix: k
  unit_time: h
  method: left
  round: 3

# ------------------------------------------------------------------------
# Thermal Power Output Integration (Total - All Modes)
# Converts instantaneous thermal power (W) to accumulated energy (kWh)
# Source: sensor.heat_pump_thermal_power_output (includes Heat, Cool, DHW)
# COMMENTED OUT FOR RESET - Uncomment after restart to recreate with 0 values
# ------------------------------------------------------------------------
- platform: integration
  source: sensor.heat_pump_thermal_power_output
  name: "Heat Pump Output Power Interval"
  unique_id: heat_pump_output_power_interval_kwh
  unit_prefix: k
  unit_time: h
  method: left
  round: 3

# ------------------------------------------------------------------------
# Space Heating Electrical Energy Integration
# Converts heating electrical power (kW) to energy (kWh)
# Source: sensor.hp_heating_electrical_power_kw (only when mode is Heat or HEAT + DHW)
# ------------------------------------------------------------------------
- platform: integration
  source: sensor.hp_heating_electrical_power_kw
  name: "HP Heating Electrical Energy (kWh)"
  unique_id: hp_heating_electrical_energy_kwh
  unit_time: h
  method: left
  round: 3

# ------------------------------------------------------------------------
# Space Heating Thermal Energy Integration
# Converts heating thermal power (kW) to energy (kWh)
# Source: sensor.hp_heating_thermal_power_kw (only when mode is Heat or HEAT + DHW)
# ------------------------------------------------------------------------
- platform: integration
  source: sensor.hp_heating_thermal_power_kw
  name: "HP Heating Thermal Energy (kWh)"
  unique_id: hp_heating_thermal_energy_kwh
  unit_time: h
  method: left
  round: 3

# ------------------------------------------------------------------------
# HVAC Load Thermal Energy Integration
# Accumulates thermal energy consumed by the HVAC system
# Source: sensor.hvac_thermal_power_used
# ------------------------------------------------------------------------
- platform: integration
  source: sensor.hvac_thermal_power_used
  name: "HVAC Thermal Energy Used"
  unique_id: hvac_thermal_energy_used
  unit_prefix: k
  unit_time: h
  method: left
  round: 3

# ------------------------------------------------------------------------
# Buffer Tank Energy Input
# Accumulates thermal energy arriving at the buffer tank from heat pump
# Only accumulates when G2 valve is directing flow to buffer tank
# Source: sensor.buffer_tank_thermal_power_input
# ------------------------------------------------------------------------
- platform: integration
  source: sensor.buffer_tank_thermal_power_input
  name: "Buffer Tank Energy Input"
  unique_id: buffer_tank_energy_input
  unit_prefix: k
  unit_time: h
  method: left
  round: 3

# ------------------------------------------------------------------------
# DHW Tank Energy Input
# Accumulates thermal energy arriving at the DHW tank from heat pump
# Only accumulates when G2 valve is directing flow to DHW tank
# Source: sensor.dhw_tank_thermal_power_input
# ------------------------------------------------------------------------
- platform: integration
  source: sensor.dhw_tank_thermal_power_input
  name: "DHW Tank Energy Input"
  unique_id: dhw_tank_energy_input
  unit_prefix: k
  unit_time: h
  method: left
  round: 3

# ------------------------------------------------------------------------
# Heat Pump Standby Thermal Loss Accumulation
# Accumulates energy lost when circulator runs but HP is off
# In heating mode: hot water cooled by outdoor coil
# In cooling mode: cool water warmed by outdoor coil
# ------------------------------------------------------------------------
- platform: integration
  source: sensor.hp_standby_thermal_loss_rate
  name: "HP Standby Thermal Loss Accumulated"
  unique_id: hp_standby_thermal_loss_accumulated
  unit_prefix: k
  unit_time: h
  method: left
  round: 3

# ------------------------------------------------------------------------
# Heat Pump Cycle Tracking (History Stats)
# DEPRECATED: These sensors have been replaced by template sensors in
# sensors/template/heat_pump_cycle_sensors.yaml
#
# These definitions are commented out to prevent unique_id conflicts
# which caused _2 duplicate entities to be created.
#
# DO NOT UNCOMMENT - Use the template sensor versions instead.
# ------------------------------------------------------------------------
# - platform: history_stats
#   name: "Heat Pump Current Cycle Duration"
#   unique_id: heat_pump_current_cycle_duration
#   entity_id: binary_sensor.heat_pump_running
#   state: "on"
#   type: time
#   start: >
#     {{ as_timestamp(states.binary_sensor.heat_pump_running.last_changed)
#        if is_state('binary_sensor.heat_pump_running', 'on')
#        else as_timestamp(now()) }}
#   end: "{{ now() }}"
#
# - platform: history_stats
#   name: "Heat Pump Current Cycle Duration Minutes"
#   unique_id: heat_pump_current_cycle_duration_minutes
#   entity_id: binary_sensor.heat_pump_running
#   state: "on"
#   type: time
#   start: >
#     {{ as_timestamp(states.binary_sensor.heat_pump_running.last_changed)
#        if is_state('binary_sensor.heat_pump_running', 'on')
#        else as_timestamp(now()) }}
#   end: "{{ now() }}"

- platform: history_stats
  name: "Heat Pump Off Time Duration"
  unique_id: heat_pump_off_time_duration
  entity_id: binary_sensor.heat_pump_running
  state: "off"
  type: time
  start: >
    {{ as_timestamp(states.binary_sensor.heat_pump_running.last_changed)
       if is_state('binary_sensor.heat_pump_running', 'off')
       else as_timestamp(now()) }}
  end: "{{ now() }}"

- platform: history_stats
  name: "Heat Pump Daily Runtime Hours"
  unique_id: heat_pump_daily_runtime_hours
  entity_id: binary_sensor.heat_pump_running
  state: "on"
  type: time
  start: "{{ now().replace(hour=0, minute=0, second=0, microsecond=0) }}"
  end: "{{ now() }}"

- platform: history_stats
  name: "Heat Pump Daily Cycle Count"
  unique_id: heat_pump_daily_cycle_count
  entity_id: binary_sensor.heat_pump_running
  state: "on"
  type: count
  start: "{{ now().replace(hour=0, minute=0, second=0, microsecond=0) }}"
  end: "{{ now() }}"

# ------------------------------------------------------------------------
# Circulator Pump Running (Without Heat Pump)
# Detects when the circulator is running but compressor is off
# This condition causes energy loss through the heat pump coil
# ------------------------------------------------------------------------
- platform: history_stats
  name: "Circulator Pump Idle Loss Duration Daily"
  unique_id: circulator_pump_idle_loss_duration_daily
  entity_id: binary_sensor.circulator_running_hp_off
  state: "on"
  type: time
  start: "{{ now().replace(hour=0, minute=0, second=0, microsecond=0) }}"
  end: "{{ now() }}"

# ------------------------------------------------------------------------
# Filter Sensor (Stabilize Shed/LC2 Power Reading)
# Filters out the dips that cause "Ignoring decreasing value" warnings.
# Source: sensor.lc_shed_lc_watts
# ------------------------------------------------------------------------
- platform: filter
  name: "Shed LC2 Consumption Power (Stable)"
  unique_id: "shed_lc2_consumption_power_stable"

  entity_id: sensor.lc_shed_lc_watts

  filters:
    - filter: outlier
      window_size: 3
      radius: 3.0
    - filter: time_simple_moving_average
      window_size: "00:00:03"

# ============================================================================
# HEAT PUMP OPTIMIZATION SENSORS
# ============================================================================

# MOVED: All heat pump optimization sensors moved to cx_optimization_sensors.yaml
# - heat_pump_running: improved logic with Water pump ON AND (Compressor running OR Heat transfer)
# - heat_pump_supply_temp: tracks supply temperature
# - heat_pump_current_cop: calculates current efficiency (COP)



# ============================================================================
# ENERGY-BASED HLC SUPPORT
# ============================================================================
- platform: statistics
  name: "House Delta T (C) - 24 Hour Mean"
  unique_id: "house_delta_t_c_24_hour_mean"
  entity_id: sensor.house_delta_t_c_raw
  state_characteristic: mean
  max_age:
    hours: 24
  sampling_size: 1000  # High sampling size for accuracy
  precision: 1

- platform: statistics
  name: "Daily Average Temperature"
  unique_id: "daily_average_temperature"
  entity_id: sensor.gw2000b_outdoor_temperature # Replace with your sensor entity
  state_characteristic: mean
  max_age:
    days: 1